package com.example.demo.application.usecases;

import com.example.demo.application.exceptions.UserNotFoundException;
import com.example.demo.domain.claim.Claim;
import com.example.demo.domain.claim.ClaimRepository;
import com.example.demo.domain.claim.ClaimStatus;
import com.example.demo.user.domain.Email;
import com.example.demo.user.domain.User;
import com.example.demo.user.domain.UserId;
import com.example.demo.user.domain.UserRepository;
import com.example.demo.user.domain.UserRole;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationEventPublisher;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@DisplayName("CreateClaimUseCase - user validation and claim creation")
class CreateClaimUseCaseTest {

    private ClaimRepository claimRepository;
    private UserRepository userRepository;
    private ApplicationEventPublisher eventPublisher;
    private MeterRegistry meterRegistry;
    private CreateClaimUseCase useCase;

    private UUID claimantId;
    private User claimant;

    @BeforeEach
    void setUp() {
        claimRepository = mock(ClaimRepository.class);
        userRepository = mock(UserRepository.class);
        eventPublisher = mock(ApplicationEventPublisher.class);
        meterRegistry = new SimpleMeterRegistry();

        useCase = new CreateClaimUseCase(
            claimRepository,
            userRepository,
            meterRegistry,
            eventPublisher
        );

        claimantId = UUID.randomUUID();
        claimant = new User(
            UserId.of(claimantId),
            "Claimant User",
            Email.of("claimant@demo.com"),
            UserRole.CLAIMANT,
            Instant.now()
        );
    }

    @Test
    @DisplayName("unknown user is rejected")
    void unknownUserIsRejected() {
        when(userRepository.findById(UserId.of(claimantId))).thenReturn(Optional.empty());

        var command = new CreateClaimCommand(
            claimantId,
            LocalDate.now().minusDays(1),
            "Kuala Lumpur, Malaysia",
            "Car accident on the highway during morning commute",
            new BigDecimal("5000")
        );

        assertThrows(UserNotFoundException.class, () -> useCase.execute(command));
    }

    @Test
    @DisplayName("valid command creates claim in SUBMITTED status")
    void validCommandCreatesClaimInSubmittedStatus() {
        when(userRepository.findById(UserId.of(claimantId))).thenReturn(Optional.of(claimant));
        when(claimRepository.save(any(Claim.class))).thenAnswer(i -> i.getArgument(0));

        var command = new CreateClaimCommand(
            claimantId,
            LocalDate.now().minusDays(1),
            "Kuala Lumpur, Malaysia",
            "Car accident on the highway during morning commute",
            new BigDecimal("5000")
        );

        Claim result = useCase.execute(command);

        assertEquals(ClaimStatus.SUBMITTED, result.getStatus());
        assertEquals(claimantId, result.getUserId());
        verify(claimRepository).save(any(Claim.class));
    }

    @Test
    @DisplayName("claim is persisted with all provided fields")
    void claimIsPersistedWithProvidedFields() {
        when(userRepository.findById(UserId.of(claimantId))).thenReturn(Optional.of(claimant));
        when(claimRepository.save(any(Claim.class))).thenAnswer(i -> i.getArgument(0));

        var incidentDate = LocalDate.now().minusDays(3);
        var command = new CreateClaimCommand(
            claimantId,
            incidentDate,
            "Penang, Malaysia",
            "Flood damaged the car engine and interior",
            new BigDecimal("12500.50")
        );

        Claim result = useCase.execute(command);

        assertEquals(incidentDate, result.getIncidentDate());
        assertEquals("Penang, Malaysia", result.getIncidentLocation());
        assertEquals("Flood damaged the car engine and interior", result.getDescription());
        assertEquals(new BigDecimal("12500.50"), result.getClaimAmount());
    }

    @Test
    @DisplayName("claim ID is auto-generated")
    void claimIdIsAutoGenerated() {
        when(userRepository.findById(UserId.of(claimantId))).thenReturn(Optional.of(claimant));
        when(claimRepository.save(any(Claim.class))).thenAnswer(i -> i.getArgument(0));

        var command = new CreateClaimCommand(
            claimantId,
            LocalDate.now().minusDays(1),
            "Kuala Lumpur, Malaysia",
            "Car accident on the highway during morning commute",
            new BigDecimal("5000")
        );

        Claim result = useCase.execute(command);

        assertEquals(claimantId, result.getUserId());
        assertEquals(LocalDate.now().minusDays(1), result.getIncidentDate());
        assertEquals(new BigDecimal("5000"), result.getClaimAmount());
        // claimId is set
        org.junit.jupiter.api.Assertions.assertNotNull(result.getClaimId());
    }
}